title: Lee Aspitarte's Personal Website
description: > # this means to ignore newlines until "baseurl:"
  Lee Aspitarte's Personal Website
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lee Aspitarte # add your name
author-img: me.png # add your photo
about-author: Physicist, Data Scientist # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: aspitarl # add your Github handle
social-linkedin: leeaspitarte # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Pagination
pagination:
  enabled: true

paginate_path: /:year/:title/

include: ['_pages']

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
